spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/sast_2022_woc?serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  # mysql 的配置


server:
  port: 8080

# mybatis 的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml