spring:
  # mysql 的配置
  datasource:
    url: jdbc:mysql://192.168,159.131:3306/sast_2022_woc?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: 210611
server:
  port: 8080
  address: 192.168,159.131

# mybatis 的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml